import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}});
const page=await context.newPage(), errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const origin=process.env.TEST_URL||'http://127.0.0.1:4173';
await mkdir('test-results',{recursive:true});
const clickStep=async label=>page.getByRole('navigation',{name:'Étapes de création'}).getByRole('button',{name:label}).click();
const download=async(name,button)=>{
  const event=page.waitForEvent('download');await button.click();const file=await event;const target=path.resolve('test-results',name);await file.saveAs(target);return readFile(target);
};
try {
  await page.goto(origin);
  await page.getByLabel('Un prénom par ligne').fill('Léna\nJean-Baptiste\nInès\nZoé\nZoé');
  await page.getByRole('button',{name:'Appliquer la liste',exact:true}).click();
  await page.getByRole('button',{name:'Appliquer la liste',exact:true}).waitFor();
  assert.ok((await page.locator('#count').textContent()).includes('5 élève'));
  await page.screenshot({path:'test-results/classe.png',fullPage:true});
  await clickStep('Modèle');await page.getByRole('button',{name:'Appel',exact:false}).click();
  await clickStep('Personnaliser');
  await page.locator('#label-preview canvas').waitFor();
  await page.getByLabel('Réglages',{exact:true}).selectOption('advanced');
  await page.getByLabel('Grande initiale séparée au-dessus').check();
  await page.locator('#label-preview canvas').waitFor();
  await page.screenshot({path:'test-results/personnalisation.png',fullPage:true});
  // Une exception sur la 3e ligne reste un JSON valide après sauvegarde.
  await page.getByLabel('Personnaliser',{exact:true}).selectOption({label:'Élève · Léna'});
  await page.getByText('3 · Cursive',{exact:true}).click();
  await page.getByLabel('Taille maximale (pt)').nth(2).fill('22');await page.getByLabel('Taille maximale (pt)').nth(2).press('Tab');
  assert.equal(await page.getByLabel('Taille maximale (pt)').nth(2).inputValue(),'22');
  const saved=await download('projet.json',page.getByRole('button',{name:'Enregistrer',exact:true}));
  const project=JSON.parse(saved.toString());assert.equal(project.students[0].style.lines[2].size,22);assert.equal(project.students.length,5);
  await page.getByRole('button',{name:'Groupes',exact:true}).click();
  await page.getByRole('button',{name:'Proposer une répartition équilibrée'}).click();
  await page.getByRole('button',{name:'Appliquer cette répartition'}).click();
  const gp=await download('groupes.pdf',page.getByRole('button',{name:'Exporter la liste en PDF'}));assert.equal(gp.subarray(0,4).toString(),'%PDF');
  await page.getByRole('button',{name:'Étiquettes',exact:true}).click();
  await clickStep('Mise en page');
  await page.getByLabel('Case 1 disponible',{exact:true}).click();
  await page.getByLabel('Case 1 utilisée',{exact:true}).waitFor();
  await clickStep('Exporter');await page.locator('#page-preview canvas').waitFor();
  const pdf=await download('etiquettes.pdf',page.getByRole('button',{name:'PDF · Toutes les pages'}));assert.equal(pdf.subarray(0,4).toString(),'%PDF');
  const png=await download('page.png',page.getByRole('button',{name:'PNG · La page affichée'}));assert.equal(png.readUInt32BE(16),2480);assert.equal(png.readUInt32BE(20),3508);
  const zip=await download('etiquettes.zip',page.getByRole('button',{name:'ZIP · Toutes les étiquettes'}));assert.equal(zip.subarray(0,2).toString(),'PK');
  await page.screenshot({path:'test-results/export.png',fullPage:true});
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  assert.deepEqual(axe.violations.map(v=>({id:v.id,description:v.description,nodes:v.nodes.map(n=>n.target)})),[]);
  for(const width of [320,768,1024,1440]){
    await page.setViewportSize({width,height:900});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`Débordement à ${width}px`);
    await page.screenshot({path:`test-results/responsive-${width}.png`,fullPage:true});
  }
  await page.getByRole('button',{name:'Activer le thème sombre'}).click();
  const dark=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(dark.violations.map(v=>v.id),[]);
  await page.screenshot({path:'test-results/sombre.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await clickStep('Élèves');
  await page.getByLabel('Importer CSV / TXT').setInputFiles({name:'classe.csv',mimeType:'text/csv',buffer:Buffer.from('Prénom;Groupe;Exemplaires\nLéna;Rouge;2\nInès;Bleu;1')});
  await expect(page.locator('#count')).toContainText('2 élève(s) · 3 étiquette(s)');
  await page.getByLabel('Importer plusieurs photos').setInputFiles({name:'Léna.png',mimeType:'image/png',buffer:png});
  await page.getByRole('button',{name:'Valider les associations'}).waitFor();
  await page.getByRole('button',{name:'Valider les associations'}).click();
  await page.getByRole('button',{name:'Photo ✓',exact:true}).click();
  await page.locator('#label-preview canvas').waitFor();
  await page.getByLabel('Importer un fond').setInputFiles({name:'fond.png',mimeType:'image/png',buffer:png});
  await page.getByLabel('Opacité',{exact:true}).waitFor();
  await page.getByLabel('Position des photos').selectOption('top');
  await page.getByLabel('Forme',{exact:true}).selectOption('circle');
  await page.getByLabel('Zoom',{exact:true}).last().fill('1.4');await page.getByLabel('Zoom',{exact:true}).last().dispatchEvent('change');
  const full=await download('projet-photos.json',page.getByRole('button',{name:'Enregistrer',exact:true}));
  const restored=JSON.parse(full.toString());assert.ok(restored.students[0].photoId);assert.equal(restored.resources.length,2);assert.equal(restored.students[0].crop.zoom,1.4);
  await page.locator('#open').setInputFiles({name:'restaurer.json',mimeType:'application/json',buffer:full});
  await page.getByRole('button',{name:'Photo ✓',exact:true}).waitFor();
  await page.locator('#open').setInputFiles({name:'invalide.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":99}')});
  await page.getByText('Impossible d’ouvrir ce fichier : Projet incompatible ou version inconnue.').waitFor();
  assert.ok((await page.locator('#count').textContent()).includes('2 élève(s)'));
  await clickStep('Modèle');
  const shared=await download('modele.json',page.getByRole('button',{name:'Partager un modèle sans élèves'}));
  assert.ok(!shared.toString().includes('Léna'));assert.ok(!shared.toString().includes('data:image'));
  await page.getByLabel('Nom du modèle à conserver').fill('Mon gabarit');await page.getByRole('button',{name:'Enregistrer les réglages actuels'}).click();
  await page.getByRole('button',{name:'Dupliquer',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Utiliser',exact:true}).count(),2);
  await page.getByRole('button',{name:'Supprimer',exact:true}).last().click();
  assert.equal(await page.getByRole('button',{name:'Utiliser',exact:true}).count(),1);
  await page.locator('#undo').click();assert.equal(await page.getByRole('button',{name:'Utiliser',exact:true}).count(),2);
  await page.locator('#redo').click();assert.equal(await page.getByRole('button',{name:'Utiliser',exact:true}).count(),1);
  await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
  // Le mode hors connexion est vérifié avec une ouverture directe du dossier.
  await context.setOffline(true);await page.goto(new URL('../index.html',import.meta.url).href);
  await page.getByLabel('Un prénom par ligne').fill('Émilie');await page.getByRole('button',{name:'Appliquer la liste',exact:true}).click();await clickStep('Personnaliser');await page.locator('#label-preview canvas').waitFor();
  assert.deepEqual(errors,[]);
  console.log('Parcours, CSV, photos/fonds, recadrage, groupes, héritage, modèles, undo/redo, JSON, PDF/PNG/ZIP, ouverture locale, accessibilité clair/sombre et 4 largeurs : OK.');
} finally {await browser.close();}
